apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: d95rlucf2-python
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe-python:86fc8355ea700596eb9d37ee7c0178ef3af1a78f@sha256:4d056ff45a9a70a68025a52594ec72d78bdc8b5e227a7f002bcd299ba884428f
          name: container-image
